routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\FullCalendarController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\AssistidoController;
use GuzzleHttp\Middleware;

Route::get('/calendario', [FullCalendarController::class, 'index'])->name('calendario.get')->middleware('auth');

Route::post('/calendario/action', [FullCalendarController::class, 'action']);

Route::get('/', [AssistidoController::class, 'index'])->middleware('auth');

/*Rotas Agenda*/
Route::get('/mediacao/criar_agenda', [AgendaController::class, 'create'])->name('mediacao.create')->middleware('auth');
Route::post('/mediacao/criar_agenda/novo', [AgendaController::class, 'store'])->name('agenda.store')->middleware('auth');
Route::get('/mediacao/agendamentos', [AgendaController::class, 'index'])->name('mediacao.agendamentos')->middleware('auth');
Route::delete('/mediacao/agendamentos/{id}', [AgendaController::class, 'destroy'])->name('agenda.destroy')->middleware('auth');
Route::get  ('/mediacao/agendamentos/{id}/edit', [AgendaController::class, 'edit'])->name('agenda.edit')->middleware('auth');

/*Rotas para agendar assistido já cadastrado*/
Route::get('/assistido/{id}/agendar/{agenda_id}',[AgendaController::class, 'criar'])->name('assistido.agendar')->middleware('auth');
Route::get('/assistido/{id}/agendar',[AgendaController::class, 'list'])->name('agenda.list')->middleware('auth');
Route::post('/agendar/{agenda_id}/info',[AgendaController::class, 'info'])->name('agenda.info')->middleware('auth');
Route::get('/agendar/{agenda_id}/novaparte',[AgendaController::class, 'novaparte'])->name('agenda.nova_parte')->middleware('auth');
Route::get('/novaparte/{agenda_id}/{id}',[AgendaController::class, 'joinAgenda'])->name('agenda.join')->middleware('auth');
Route::get ('/assistido/{assistido_id}/agenda/{agenda_id}/delete', [AgendaController::class, 'delete'])->name('delete.parte')->middleware('auth');

/*Rotas Assistido*/
Route::get  ('/assistido', [AssistidoController::class, 'list'])->name('assistido.list')->middleware('auth');
Route::get  ('/assistido/{id}', [AssistidoController::class, 'create'])->name('assistido.create')->middleware('auth');
Route::get ('/assistido/{id}/novo', [AssistidoController::class, 'store'])->name('assistido.store')->middleware('auth');
Route::get  ('/assistido/{id}/edit', [AssistidoController::class, 'edit'])->name('assistido.edit')->middleware('auth');
Route::post ('/assistido/{id}/update', [AssistidoController::class, 'update'])->name('assistido.update')->middleware('auth');
Route::delete('/assistido/{id}', [AssistidoController::class, 'destroy'])->name('assistido.destroy')->middleware('auth');
Route::get  ('/assistido/{id}/info', [AssistidoController::class, 'show'])->name('assistido.info')->middleware('auth');



//rotas para criar assistido antes de agendar;
Route::get ('/novo/assistido', [AssistidoController::class, 'novo'])->name('assistido.novo')->middleware('auth');
Route::post  ('/assistido/criar', [AssistidoController::class, 'criar'])->name('assistido.criar')->middleware('auth');

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/agendar.blade.php
@extends('layouts.main')

@section('title', 'Meus agendamentos')

@section('content')    

    <div class="container-fluid">
        <div class="row">
            @if(session('msg'))
            <p class="msg"> {{session('msg')}}</p>
            @endif
        </div>
    </div>
    <div style="margin: 50px">
   {{--@if ((Auth::user()->user_type) == 1)<a  href="{{url ('/mediacao/criar_agenda')}}"><button class="btn btn-dark ">Disponibilizar novo horario na agenda</button></a><br>@endif--}}
    <a class="btn btn-warning mt-5" href="{{ route('assistido.list')}}">Pesquisar/Cadastrar assistido</a>
    </div>

    <div class="col-md10 offset-md-1 dashboard-title-container" style="margin-right: 160px">
        <h2>Meus agendamentos</h2>
    </div>
    <div class="col-md10 offset-md-1 dashboard-title-container pb-5" style="margin-right: 160px">
    @php
    $i = 1;
    @endphp
        @if(count($agendas) > 0)
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Dia</th>
                    <th scope="col">Horários</th>
                </tr>
            </thead>
        
        <tbody>

    @foreach($agendas as $agenda)
        @if($loop->first)
            @php 
                $day = date('d/m', strtotime($agenda -> start));  //Igualando o primeiro dia com o dia atual, para comparar nos próximos loops
                $l_start = $agenda->start;
                $l_assistido = $agenda->assistido_id;
            @endphp 
            <tr>
                <th scope="row">{{$i}}</th>
                <td>{{$agenda->dia}} - {{date('d/m', strtotime($agenda->start))}}</td>
                <td>@if(($agenda -> assistido_id) == null)
                <a href="#"class="btn btn-success"> {{date('H:i', strtotime($agenda->start))}} - {{$agenda->vag_h}} </a>
            @else 
                @if(($agenda -> assistido_id) == null)
                    <a href="#"class="btn btn-primary"> {{date('H:i', strtotime($agenda->start))}} - {{$agenda->vag_h}} </a>
                @else
                    @if(($agenda->Status)==2) <a href="{{route('assistido.info',$agenda->Assistido-> id)}}"class="btn btn-secondary">
                    <abbr class="text-decoration-none" title="{{$agenda->Assistido->nome}}">{{date('H:i', strtotime($agenda->start))}}
                    @elseif(($agenda->Status)==1) <a href="{{route('assistido.info',$agenda->Assistido->id)}}"class="btn btn-warning">
                    <abbr class="text-decoration-none" title="{{$agenda->Assistido->nome}}">{{date('H:i', strtotime($agenda->start))}}    
                @endif
                </abbr></a>
            @endif     
        @endif     
                
        @endif
        @if($day != date('d/m', strtotime($agenda -> start)))                           <!--Abrimos nova linha, caso seja um novo dia-->  <!--Para mostrar apenas um evento por horario-->
                @php $i+=1;@endphp                                                      <!--Contagem de linhas da tabela-->
                    </td>                               
                </tr>
                <tr>
                    <th scope="row">{{$i}}</th>
                    <td>{{$agenda->dia}} - {{date('d/m', strtotime($agenda->start))}}</td>
                    <td>
        @endif
        @if($l_start != $agenda->start || $l_assistido != $agenda->assistido_id)  <!--Para mostrar apenas um evento por horario-->
            @if(($agenda -> assistido_id) == null)
                <a href="#"class="btn btn-success"> {{date('H:i', strtotime($agenda->start))}} - {{$agenda->vag_h}} </a>
            @else
            @if(($agenda->Status)==2) <a href="{{route('assistido.info',$agenda->Assistido-> id)}}"class="btn btn-secondary">
                <abbr class="text-decoration-none" title="{{$agenda->Assistido->nome}}">{{date('H:i', strtotime($agenda->start))}}
            @elseif(($agenda->Status)==1) <a href="{{route('assistido.info',$agenda->Assistido-> id)}}"class="btn btn-warning">
                <abbr class="text-decoration-none" title="{{$agenda->Assistido->nome}}">{{date('H:i', strtotime($agenda->start))}}
        @endif
        </abbr></a>    
        @endif
        @else
        @endif   
        @php 
            $l_start = $agenda -> start;
            $l_assistido = $agenda -> assistido_id;
            $day = date('d/m', strtotime($agenda -> start)); 
        @endphp    
    @endforeach
                </td>
            </tr>
        </tbody>


        @else
            <p>Você ainda não criou um horario de atendimento.</p>
        @endif
    </div>
    {{--@endif--}}
        <div class="mx-auto" >
            {{$agendas->links()}}
        </div>
@endsection
{{--@extends('layouts.main')

@section('title', 'Agendar')

@section('content')  

    <a class="btn btn-dark mt-5" href="{{ route('assistido.list')}}">Pesquisar/Cadastrar assistido</a>
    
    <div id="events-container" class="col-md-12">
        <h2>Próximas vagas e horários</h2>
        

    @foreach($agendas as $agenda)
        @if($loop->first)                                                   <!-- Se for o primeiro loop, já criamos o card com o dia-->
            @php $day = date('d/m', strtotime($agenda -> start)) @endphp    <!-- Igualando o primeiro dia com o dia atual, para comparar nos próximos loops-->
            @php 
                $l_start = $agenda -> start;
                $l_assistido = $agenda -> assistido_id;
            @endphp
                <div id="cards-container">                                  <!-- Container para os cards-->
                <div class="row d-flex justify-content-center">
                    <div class = "card col-md-4">
                        <div class="card-body">
                            {{$agendas->links()}}
                            <h5 class="card-date">{{$agenda -> dia}}<br>dia {{date('d/m', strtotime($agenda -> start))}}</h5><!-- Imprimindo o dia e mês-->
                            @if (isset($agenda -> assistido_id))
                                <p class="datas">Agendado: {{date('H:i', strtotime($agenda -> start))}}<br>{{$agenda->Assistido->nome }} @if(($agenda->Status)==2) <ion-icon name="checkmark-done-outline"></ion-icon>@elseif(($agenda->Status)==1) <ion-icon name="checkmark-outline"></ion-icon> @endif<br>  
                                    <a href="{{route('assistido.info',$agenda->Assistido-> id)}}" class="btn btn-secondary"> info </a>
                                </p>
                            @else
                                <p class="datas"> de {{date('H:i', strtotime($agenda -> start))}} <br> até {{date('H:i', strtotime($agenda -> end))}} <br>  
                                    <a href="#" class="btn btn-success"> {{$agenda -> vag_h}} vaga(s) </a>
                                </p>
                            @endif
                            
        @else
            @if($l_start != $agenda -> start || $l_assistido != $agenda -> assistido_id)  <!--Para mostrar apenas um evento por horario-->
                    @if($day != date('d/m', strtotime($agenda -> start)))    <!-- Se for um novo dia, criaremos outro card com o próximo dia-->
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="cards-container">
                        <div class="row d-flex justify-content-center">
                            <div class = "card col-md-4">
                                <div class="card-body">
                                    <h5 class="card-date">{{$agenda -> dia}}<br>dia {{date('d/m', strtotime($agenda -> start))}}</h5>
                    @endif
                @if($agenda->vag_h>0)
                    @if (isset($agenda -> assistido_id))
                    <p class="datas">Agendado: {{date('H:i', strtotime($agenda -> start))}}<br>Assistido: {{$agenda->Assistido->nome }} @if(($agenda->Status)==2) <ion-icon name="checkmark-done-outline"></ion-icon>@elseif(($agenda->Status)==1) <ion-icon name="checkmark-outline"></ion-icon> @endif<br>  
                        
                        <a href="{{route('assistido.info',$agenda->Assistido-> id)}}" class="btn btn-secondary"> info </a>
                    </p>
                    @else
                    <p class="datas"> de {{date('H:i', strtotime($agenda -> start))}} <br> até {{date('H:i', strtotime($agenda -> end))}} <br>  
                        <a href="" class="btn btn-success"> {{$agenda -> vag_h}} vaga(s) </a>
                    </p>
                    @endif
                @endif
                    @php 
                        $day = date('d/m', strtotime($agenda -> start)); 
                        $l_start = $agenda -> start;
                        $l_assistido = $agenda -> assistido_id;
                    @endphp
            @endif
        @endif    
    @endforeach

    @if(count($agendas) == 0)
        <p>Não há agendamentos disponíveis</p>
    @endif
    


@endsection  --}}

resources/views/agendar_assistido.blade.php
@extends('layouts.main')

@section('title', 'Agendamento')

@section('content')    

    <div class="container-fluid">
        <div class="row">
            @if(session('msg'))
            <p class="msg"> {{session('msg')}}</p>
            @endif
        </div>
    </div>

    <div class="col-md10 offset-md-1 dashboard-title-container" style="margin-right: 160px">
        <h2>Agendando assistido</h2>

        <a href="{{route('assistido.novo')}}" class="btn btn-secondary edit-btn">Cadastrar outro assistido</a>
    </div>
        <p>Ou, continue e escolha um horário de atendimento...</p>
    <div class="col-md10 offset-md-1 dashboard-title-container pb-5" style="margin-right: 160px">
    @php
    $i = 1;
    @endphp
        @if(count($agendas) > 0)
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Dia</th>
                    <th scope="col">Horários</th>
                </tr>
            </thead>
        
        <tbody>

    @foreach($agendas as $agenda)
        @if($loop->first)
            @php 
                $day = date('d/m', strtotime($agenda -> start));
                $l_start = $agenda -> start;
                $l_assistido = $agenda -> assistido_id;
            @endphp
            <tr>
                <th scope="row">{{ $i }}</th>
                <td>{{$agenda->dia}} - {{date('d/m', strtotime($agenda->start))}}</td>
                <td> @if(($agenda -> assistido_id) == null)
                    <a href="{{route('assistido.agendar', [$assistido_id, 'agenda_id'=> $agenda->id]) }}" class="btn btn-success edit-btn"> {{date('H:i', strtotime($agenda->start))}} </a>
                @endif                
        @endif
        @if($day != date('d/m', strtotime($agenda -> start)))                           <!--Abrimos nova linha, caso seja um novo dia-->
            @php $i+=1;@endphp                                                      <!--Contagem de dias-->
                </td>                               
            </tr>
            <tr>
                <th scope="row">{{$i}}</th>
                <td>{{$agenda->dia}} - {{date('d/m', strtotime($agenda->start))}}</td>
                <td>
        @endif
        @if($l_start != $agenda -> start || $l_assistido != $agenda->assistido_id)  <!--Para mostrar apenas um evento por horario-->
            @if(($agenda -> assistido_id) == null)
                <a href="{{route('assistido.agendar', [$assistido_id, 'agenda_id'=> $agenda->id]) }}" class="btn btn-success edit-btn"> {{date('H:i', strtotime($agenda->start))}} </a>
            @endif   
        @endif
        @php 
            $l_start = $agenda -> start;
            $l_assistido = $agenda -> assistido_id;
            $day = date('d/m', strtotime($agenda -> start)); 
        @endphp 
    @endforeach
                </td>
            </tr>
        </tbody>
    </div>
    @endif
        <div class="mx-auto" >
            {{$agendas->links()}}
        </div>
@endsection

resources/views/assistido.blade.php
@extends('layouts.main')

@section('title', 'Agendar')

@section('content')  


<div id="search-container" class="col-md-12 justify-content-center">
    <h2>Buscar assistido</h2>
    <form action="{{route('assistido.list')}}" method="GET">
        <input type="text" id="search" name="search" placeholder="Procure pelo Nome ou CPF"> <br>
        <button type="submit" class="btn btn-warning btn-sm mt-1">Pesquisar</button>
    </form>
</div>

<div class="listAssistidos">
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Nascimento</th>
            <th scope="col">Cpf</th>
            <th scope="col">E-mail</th>
            <th scope="col">Telefone</th>
            <th scope="col">Ação</th>
        </tr>
    </thead>
@foreach ($assistidos as $assistido)
        @php
        $cpf = preg_replace("/(\d{3})(\d{3})(\d{3})(\d{2})/", "\$1.\$2.\$3-\$4", $assistido -> cpf);
        $tel = preg_replace("/(\d{0})(\d{2})(\d{5})(\d{4})/", "\$1(\$2)\$3-\$4", $assistido -> telefone);
        @endphp
        <tbody>
            <tr>
                <th scope="row">{{ $loop->iteration }}</th>
                <td>{{$assistido->nome}}</td>
                <td>@if($assistido->nasc != null){{date('d/m/Y', strtotime($assistido -> nasc))}} @else - @endif</td>
                <td>{{$cpf}}</td>
                <td>{{$assistido->email}}</td>
                <td>{{$tel}}</td>
                <td>
                    <a href="{{route('assistido.info', $assistido-> id)}}"class="btn btn-secondary btn-sm"> info </a>
                    <a href="{{ route('agenda.list', $assistido-> id)}}"class="btn btn-success btn-sm"> Agendar </a>
                </td>
            </tr>
        </tbody>
    
@endforeach
@if(isset($search))
    @if((count($assistidos)==0))
        <p>Não foi encontrado um assistido cadastrado com esse nome/CPF</p> 
    @endif
@endif
    <a href="{{route('assistido.novo')}}"class="btn btn-success btn-sm"> Cadastrar </a>  
    </div>
    
    <div class="mt-3 mx-auto" style="width: 150px">
    {{$assistidos->links()}}
    </div>

@endsection

resources/views/assistidos_novaparte.blade.php
@extends('layouts.main')

@section('title', 'Adicionando nova parte')

@section('content')  


<div id="search-container" class="col-md-12 justify-content-center">
    <h2>Buscar assistido</h2>
    <form action="{{route('agenda.nova_parte',$agenda_id)}}" method="GET">
        @csrf
        <input type="hidden" name="id" value="{{$agenda_id}}">
        <input type="text" id="search" name="search" placeholder="Procure pelo Nome ou CPF"> <br>
        <button type="submit" class="btn btn-warning btn-sm mt-1">Pesquisar</button>
    </form>
</div>

<div class="listAssistidos">
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Nascimento</th>
            <th scope="col">Cpf</th>
            <th scope="col">E-mail</th>
            <th scope="col">Telefone</th>
            <th scope="col">Ação</th>
        </tr>
    </thead>
@foreach ($assistidos as $assistido)
        @php
        $cpf = preg_replace("/(\d{3})(\d{3})(\d{3})(\d{2})/", "\$1.\$2.\$3-\$4", $assistido -> cpf);
        $tel = preg_replace("/(\d{0})(\d{2})(\d{5})(\d{4})/", "\$1(\$2)\$3-\$4", $assistido -> telefone);
        @endphp
        <tbody>
            <tr>
                <th scope="row">{{ $loop->iteration }}</th>
                <td>{{$assistido->nome}}</td>
                <td>@if($assistido->nasc != null){{date('d/m/Y', strtotime($assistido -> nasc))}} @else - @endif</td>
                <td>{{$cpf}}</td>
                <td>{{$assistido->email}}</td>
                <td>{{$tel}}</td>
                <td>
                    <a href="{{route('agenda.join',['id'=>$assistido->id,'agenda_id'=>$agenda_id])}}"class="btn btn-success btn-sm"> Adicionar a conciliação</a>
                </td>
            </tr>
        </tbody>
    
@endforeach
@if(isset($search))
    @if((count($assistidos)==0))
        <p>Não foi encontrado um assistido cadastrado com esse nome/CPF</p> 
    @endif
@endif
    <a href="{{route('assistido.create',['id'=>$agenda_id])}}"class="btn btn-success btn-sm"> Cadastrar </a>  
    </div>
    
    <div class="mt-3 mx-auto" style="width: 150px">
    {{$assistidos->links()}}
    </div>

@endsection

resources/views/cadastroassistido.blade.php
@extends('layouts.main')

@section('tile', 'Cadastro')

@section('content')


        <div class="info-cadastro">
            <p class="card-date">Adicionando parte para atendiamento:<br> {{$agenda -> dia}} dia 
                {{date('d/m', strtotime($agenda -> start))}} <br> de {{date('H:i', strtotime($agenda -> start))}} até {{date('H:i', strtotime($agenda -> end))}}</p>
        </div>

<form action="{{ route('assistido.store',$agenda -> id) }}" method="get">
    @csrf
    <input type="hidden" name="agenda_id" value="{{$agenda['id']}}">
    <div class="cadastro"><br>
        <div class="cadastron">
            <label for="nome"><b>Nome:</b></label>
            <input type="text" id="nome" name="nome" required>
        </div><br>
        <div class="cadastrod">
            <label for="nasc"><b>Data de nascimento:</b>&nbsp;<input type="date"  id="nasc" name="nasc"></label>
            
        </div> <br>
        <div class="cadastrocpf"> 
            <label for="cpf"><b>CPF:</b></label>
            <input type="text" id="cpf" name="cpf" maxlength="11" required>
        </div> <br>
        <div class="cadastrotel"> 
            <label for="telefone"><b>Telefone:</b></label>
            <input type="text" id="telefone" name="telefone" maxlength="11" required>
        </div> <br>
        <div class="cadastroemail"> 
            <label for="email"><b>E-mail:</b></label>
            <input type="text" id="email" name="email" required>
        </div> <br>
        <div class="form-group">
            <p>
                <input type="submit" class="btn btn-success" value="Cadastrar" >
                <input type="reset" class="btn btn-secondary" value="Limpar" >
            </p>
        </div>
    </div>
</form>


@endsection

resources/views/cadastroassistido_semagendamento.blade.php
@extends('layouts.main')

@section('tile', 'Cadastro')

@section('content')

<form action="{{ route('assistido.criar')}}" method="POST">
    @csrf
<div class="cadastro"><br>
    <div class="cadastron">
        <label for="nome"><b>Nome:</b></label>
        <input type="text" id="nome" name="nome" required>
    </div><br>
    <div class="cadastrod">
        <label for="nasc"><b>Data de nascimento:</b>&nbsp;<input type="date"  id="nasc" name="nasc"></label>
        
    </div> <br>
    <div class="cadastrocpf"> 
        <label for="cpf"><b>CPF:</b></label>
        <input type="text" id="cpf" name="cpf" maxlength="11" required>
    </div> <br>
    <div class="cadastrotel"> 
        <label for="telefone"><b>Telefone:</b></label>
        <input type="text" id="telefone" name="telefone" maxlength="11" required>
    </div> <br>
    <div class="cadastroemail"> 
        <label for="email"><b>E-mail:</b></label>
        <input type="text" id="email" name="email" required>
    </div> <br>
        <div class="form-group">
        <p>
            <input type="submit" class="btn btn-success" value="Cadastrar" >
            <input type="reset" class="btn btn-secondary" value="Limpar" >
        </p>
    </div>
</div>
</form>


@endsection

resources/views/editassistido.blade.php
<@extends('layouts.main')

@section('tile', 'Atualizando cadastro')

@section('content')


    <div class="info-cadastro">
        <p class="card-date">Atualizando dados do Assistido {{$assistido->nome }}</p>
    </div>
    <form action="{{ route('assistido.update',$assistido -> id) }}" method="POST">
    @csrf
<div class="cadastro"><br>
    <div class="cadastron">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" value="{{$assistido->nome}}" required>
    </div><br>
    <div class="cadastrod">
        <label for="nasc">data de nascimento: &nbsp;<input  value="{{$assistido->nasc}}" type="date"  id="nasc" name="nasc"></label>
        
    </div> <br>
    <div class="cadastrocpf"> 
        <label for="cpf">cpf:</label>
        <input type="text" id="cpf" name="cpf" maxlength="11"value="{{$assistido->cpf}}">
    </div> <br>
    <div class="cadastrotel"> 
        <label for="telefone">telefone:</label>
        <input type="text" id="telefone" name="telefone" maxlength="11"value="{{$assistido->telefone}}">
    </div> <br>
    <div class="cadastroemail"> 
        <label for="email">e-mail:</label>
        <input type="text" id="email" name="email"value="{{$assistido->email}}">
    </div> <br>
        <div class="form-group">
        <p>
            <input type="submit" class="btn btn-secondary" value="Confirmar alterações" >
        </p>
    </div>
</div>
</form>
<form action="{{ route('assistido.destroy', $assistido->id) }}" method="POST">
    @csrf
    @method('DELETE')
    <button type="submit" class="btn btn-danger delete-btn">Deletar assistido</button>
</form>
{{--<form action="{{ route('agenda.destroy', $assistido->id) }}" method="POST">
    @csrf
    @method('DELETE')

    <button type="submit" class="btn btn-danger delete-btn">Cancelar agendamento</button>
</form>--}}
</form>


@endsection

resources/views/info_form.blade.php
@extends('layouts.main')

@section('title', 'Informações assistido')

@section('content')    


<form action="{{ route('agenda.info', $agenda_id) }}" method="POST">
@csrf
<div> <br>
    <label for="info">Informações sobre o agendamento:</label><br><br>
    <textarea id="info" name="info"></textarea>
</div> <br>
<input type="submit" class="btn btn-success" value="Agendar" >
</form>
    


@endsection

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>